### ISSUE TITLE
Ygg - Missing results

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#142]
Hi @elgatito 
I have seen that you fixed YGG provider, thanks!

But there are missing results according to the site.

For example I want to see this episode: Vikings S02E10
When I search for season pack, there are some results, like here:
https://www2.yggtorrent.pe/engine/search?name=vikings+s02&do=search

But when I press on the episode for searching, it found only one result.

Kodi Log:
https://paste.ubuntu.com/p/62B92ChjJD

Images:
Single result:
![image](https://user-images.githubusercontent.com/13424257/65976793-60ef9300-e479-11e9-9a24-91f411f1fea3.png)

From the site:
![image](https://user-images.githubusercontent.com/13424257/65976895-90060480-e479-11e9-8dd3-9d059c90589e.png)

Elementum 0.1.40
Burst 0.0.39
Kodi 17.6

**Comment by elgatito** [comment]
In the log your search url is this - https://www2.yggtorrent.pe/engine/search?do=search&name=vikings+s2-
And there are no results on that page.
Check your overrides or any other modifications.

**Comment by burekas7** [comment]
As I see when the search url is "S02" it's ok, so the problem is that it searches for "s2".
(It seems that the additional "-" char is not the probelm.

I didn't find any changes in my folder or any override file. (Where do I need to check?)
How can I restore to the default?

And just to understand: The first query is for the specific episode and then it tries also for the season?

These are the search urls from the log:
https://www2.yggtorrent.pe/engine/search?do=search&name=vikings+s02e10
https://www2.yggtorrent.pe/engine/search?do=search&name=vikings+02x01%7CS02
https://www2.yggtorrent.pe/engine/search?do=search&name=vikings+s2-

**Comment by elgatito** [comment]
Please, try version 0.0.40. 
Fallback query for yggtorrent was fixed. And trailing "-" was removed.

**Comment by burekas7** [comment]
Some problems

1. I get this error notification after the update when kodi start.
Is it connected to the update?
![image](https://user-images.githubusercontent.com/13424257/66272126-5a448f80-e86e-11e9-94e5-47d6fcef737c.png)

2. There is sometimes a problem that there are some "problematic" providers or they didn't respond, and instead of ignoring them and show the results from the rest, it crush the all search process and doesn't show the results from the other and actually show the "Playback Failed" dialog.
(But it seems more Elementum issue then Burst)

3. Regarding (2): it sometimes show this error:
![image](https://user-images.githubusercontent.com/13424257/66272134-76e0c780-e86e-11e9-8928-7424dd5e6d98.png)

And also it seems that there is a problem with other providers, iclude Ygg:
![image](https://user-images.githubusercontent.com/13424257/66272110-426d0b80-e86e-11e9-8f79-ac4b7756901e.png)

4.  Regarding (3) It still doesn't show results from ygg.

Kodi Log:
https://paste.ubuntu.com/p/YNRT27JRj8

**Comment by elgatito** [comment]
1. No. Commoncache is not used in plugins.
2. Then you manually changed default settings that do take care to have correct timeouts, so that slow providers do not influence others. Burst timeout should be less than Elementum's.
3. That comes from No.2. One slow provider dismisses all others.

**Comment by burekas7** [comment]
1. Strange, the "Commoncache" error notification start to show up since the update of Burst.
2. But why after this update it start to have the problem with the providers consistantly? The settings are the same as it was.

And my settings are ok, Elementum timeout is 25, Burst timeout is 20.
I still get the providers error and the "Playback Failed" dialog.
I seems that something was changed in Burst the makes it happens more then before.

Log:
https://paste.ubuntu.com/p/Ntv3x8F7tx

**Comment by burekas7** [comment]
There is the same issue of fallback of ETTV provider:

https://www.ettv.to:443/torrents-search.php?search=vikings%20s2&cat=0&incldead=0&lang=0

there is "s2" instead of "s02"

**Comment by burekas7** [comment]
I increased the timeouts: Elementum 35, Burst 30 and now it's ok.
I don't know why, the seach time seems to be slower then it was according to the logs.

**Comment by burekas7** [comment]
> There is the same issue of fallback of ETTV provider:
> 
> https://www.ettv.to:443/torrents-search.php?search=vikings%20s2&cat=0&incldead=0&lang=0
> 
> there is "s2" instead of "s02"
> 
> EDIT: I open a seperated issue for this - #145

@elgatito 
Can you please check this request regarding "ETTV"?

Thanks.

**Comment by elgatito** [comment]
I have changed fallbacks for all providers, including Ygg and ETTV. Will be available in the next version.

**Comment by elgatito** [comment]
Burst 0.0.41 is already available.

**Comment by elgatito** [comment]
Please, try v0.0.42.

**Comment by burekas7** [comment]
See my comment here regarding ETTV and MagnetDL
https://github.com/elgatito/script.elementum.burst/issues/145#issuecomment-569929366

**Comment by elgatito** [comment]
ETTV fixed in v0.0.43.
Thepiratebay is also modified with proper language in the query.

I have enabled GLO and TPB and both torrents are in the list.

**Comment by burekas7** [comment]
I related to ETTV here:
https://github.com/elgatito/script.elementum.burst/issues/145#issuecomment-569959554

And regarding GLO & TPB here:
https://github.com/elgatito/script.elementum.burst/issues/157#issuecomment-569959078

---

I have a general question regarding RARBG:

I see they have these mirrors urls:
1) rarbg.is
2) rarbgmirror.com

But why are you are using somthing different, such as:
https://torrentapi.org/pubapi_v2.php?mode=search&search_string=the+witcher+s01e02&category=1;18;41;49&format=json_extended&app_id=script.elementum.burst&token=3pc7xnl1vj
(Which is ok, I get results. Just curios)
