### ISSUE TITLE
Private trackers

### ISSUE THREAD

**Issue by jessev83-1** [elgatito/script.elementum.burst#59]
@elgatito  these private trackers should be checked. There is some trackers what isnt working. Example torrentleech not working, wont give any result and filelist not working. Filelist give alot results with seeders but wont start downloading, hangs to 0%. Torrentleech login succesfull because i checked from logfile but wont give results. Whole private tracker list should be checked.

**Comment by elgatito** [comment]
filelist is working fine, you need to change useragent in Elementum to something like utorrent, they have a whitelist.

You can check all private trackers if you want to. I don't have even half of logins.

**Comment by Jezze83** [comment]
Btw, elementum wont support season packs, right? If i download pack, i cant choose episode? Is it possible get that support? I try find out those providers what arent working and i report here.

**Comment by elgatito** [comment]
>  If i download pack, i cant choose episode
When you select a multi-file torrent you are asked to select one file to download. Elementum does not download all files.

**Comment by Jezze83** [comment]
I just tested many differents user-agents for filelist and still not downloading anything. I also rebooted computer when swithing UA.

**Comment by Jezze83** [comment]
Nvm, there was old user-agents in elementum settings. With transmission works fine.

**Comment by Jezze83** [comment]
@elgatito  I try fix torrentleech for burst but i dont understand why i dont get any result. I get correct url for searching but it wont list anything. Maybe problem is from parser? I edited cookies and pass hash off from log.

14:20:57.936 T:9284   DEBUG: [script.elementum.burst] Decoding charset from utf-8-sig for 'https://www.torrentleech.org/user/account/login/'
14:20:57.942 T:9284   DEBUG: [script.elementum.burst] Status for 'https://www.torrentleech.org/user/account/login/' : 200
14:20:57.942 T:9284  NOTICE: [script.elementum.burst] [torrentleech] Login successful
14:20:57.943 T:9284  NOTICE: [script.elementum.burst] >      TorrentLeech search URL: https://www.torrentleech.org/torrents/browse/index/categories/8,9,11,37,43,14,12,13,41,47,15,29/query/ready%20player%20one
14:20:57.943 T:9284   DEBUG: [script.elementum.burst] Opening URL: 'https://www.torrentleech.org/torrents/browse/index/categories/8,9,11,37,43,14,12,13,41,47,15,29/query/ready%20player%20one'
14:20:57.948 T:9284   DEBUG: [script.elementum.burst] Cookies for 'https://www.torrentleech.org/torrents/browse/index/categories/8,9,11,37,43,14,12,13,41,47,15,29/query/ready%20player%20one': <LWPCookieJar[Cookie(version=0, name='__cfduid', value='**********', port=None, port_specified=False, domain='.torrentleech.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1562928294, discard=False, comment=None, comment_url=None, rest={'HttpOnly': 'None'}, rfc2109=False), Cookie(version=0, name='member_id', value='375348', port=None, port_specified=False, domain='.torrentleech.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=2147483646, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='pass_hash', value='**********', port=None, port_specified=False, domain='.torrentleech.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=2147483646, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='tlpass', value='70eccea2c9b79995818f645a39898d121070be8f', port=None, port_specified=False, domain='.torrentleech.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=2147483646, discard=False, comment=None, comment_url=None, rest={'httponly': 'None'}, rfc2109=False), Cookie(version=0, name='tluid', value='1121314', port=None, port_specified=False, domain='.torrentleech.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=2147483646, discard=False, comment=None, comment_url=None, rest={'httponly': 'None'}, rfc2109=False), Cookie(version=0, name='PHPSESSID', value='***************', port=None, port_specified=False, domain='www.torrentleech.org', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>
14:20:58.025 T:7796   DEBUG: [script.elementum.burst] Timer: 0s / 9s
14:20:58.276 T:7796   DEBUG: [script.elementum.burst] Timer: 1s / 9s
14:20:58.540 T:9284   DEBUG: Previous line repeats 1 times.
14:20:58.540 T:9284   DEBUG: [script.elementum.burst] Decoding charset from utf-8-sig for 'https://www.torrentleech.org/torrents/browse/index/categories/8,9,11,37,43,14,12,13,41,47,15,29/query/ready%20player%20one'
14:20:58.541 T:9284   DEBUG: [script.elementum.burst] Status for 'https://www.torrentleech.org/torrents/browse/index/categories/8,9,11,37,43,14,12,13,41,47,15,29/query/ready%20player%20one' : 200
14:20:58.541 T:9284   DEBUG: [script.elementum.burst] [torrentleech] Accepted resolutions: ['filter_480p', 'filter_720p', 'filter_1080p', 'filter_2k', 'filter_4k']
14:20:58.541 T:9284   DEBUG: [script.elementum.burst] [torrentleech] Accepted release types: ['480p', u'480\u0440', 'xvid', 'dvd', 'dvdrip', 'hdtv', '720p', u'720\u0440', 'hdrip', 'bluray', 'blu_ray', 'brrip', 'bdrip', 'hdtv', '1080p', u'1080\u0440', '1080i', 'fullhd', '_fhd_', '_2k_', '1440p', u'1440\u0440', '_4k_', '2160p', u'2160\u0440', '_dvd_', 'dvdrip', 'vcdrip', 'hdrip', 'hdtv', 'screener', '_scr_', 'webdl', 'webrip', 'web_dl', 'dlrip', '_yts_', 'dvdscr', 'brrip', 'bdrip', 'bluray']
14:20:58.541 T:9284   DEBUG: [script.elementum.burst] [torrentleech] Blocked release types: ['workprint', 'trailer', u'\u0442\u0440\u0435\u0439\u043b\u0435\u0440', u'\u0442\u0438\u0437\u0435\u0440', 'telesync', '_ts_', '_tc_', '_3d_', '_cam_', 'hdcam', 'vhsrip', '_tvrip_', 'satrip']
14:20:58.542 T:9284   DEBUG: [script.elementum.burst] [torrentleech] Minimum size: 0.0 GB
14:20:58.542 T:9284   DEBUG: [script.elementum.burst] [torrentleech] Maximum size: 100.0 GB
14:20:58.542 T:9284   DEBUG: [script.elementum.burst] Extracting torrents from torrentleech using definitions: {u'show_query': u'/newfilter/2/facets/category%253ATV', u'season_keywords2': u'{title:original} s{season:2}', u'movie_extra': u'', u'color': u'FF076700', u'parser': {u'peers': u"item(tag='td', order=8)", u'name': u"item(name='a', order=2)", u'seeds': u"item(tag='td', order=7)", u'row': u"find_once('table', ('id', 'torrenttable')).find_all('tr')", u'infohash': u'', u'torrent': u"item(tag='a', attribute='href', order=5).replace('/download', 'https://www.torrentleech.org/download')", u'size': u"item(tag='td', order=5)"}, u'private': True, u'tv_extra': u'', u'anime_query': u'/categories/34', u'tv_extra2': u'', u'tv_keywords2': u'', u'general_query': u'', u'season_extra': u'', u'season_query': u'/newfilter/2/facets/category%253ATV', u'tv_keywords': u'{title:original} s{season:2}e{episode:2}', 'alias': '', u'base_url': u'https://www.torrentleech.org/torrents/browse/index', u'anime_keywords': u'{title:original} {episode}', u'season_extra2': u'', u'anime_extra': u'', u'movie_keywords': u'{title:original}', u'movie_query': u'/categories/8,9,11,37,43,14,12,13,41,47,15,29/query/QUERY', u'login_object': u"{'username': USERNAME, 'password': PASSWORD}", 'root_url': u'https://www.torrentleech.org', u'subpage': False, u'general_keywords': u'{title:original}', u'name': u'TorrentLeech', u'language': None, u'general_extra': u'', u'login_failed': u'Invalid', u'separator': u'%20', u'login_path': u'/user/account/login/', u'season_keywords': u'{title:original} season {season:2}'}
14:20:58.555 T:9284   DEBUG: [script.elementum.burst] [torrentleech] Parser: {u'peers': u"item(tag='td', order=8)", u'name': u"item(name='a', order=2)", u'seeds': u"item(tag='td', order=7)", u'row': u"find_once('table', ('id', 'torrenttable')).find_all('tr')", u'infohash': u'', u'torrent': u"item(tag='a', attribute='href', order=5).replace('/download', 'https://www.torrentleech.org/download')", u'size': u"item(tag='td', order=5)"}
14:20:58.557 T:9284   DEBUG: [script.elementum.burst] >>>>>> torrentleech would send 0 torrents to Elementum <<<<<<<
14:20:58.558 T:9284  NOTICE: [script.elementum.burst] >>     TorrentLeech returned  0 results in 1.3 seconds

**Comment by elgatito** [comment]
I have fixed torrentleech, it will be available in the next version.

**Comment by Jezze83** [comment]
Good to know, problem is with parser because i dont know how to read those. I wanna make custom providers and fix current. Dont know how to user parsers.

**Comment by Jezze83** [comment]
Can you give that fixed version so i can compare and figure out how to read these parsers?

**Comment by elgatito** [comment]
Update burst plugin, fix is there.

**Comment by Jezze83** [comment]
Yes i saw that and compared, i still dont have any clue about there parsers. What file should i edit if i want add my own trackers?

**Comment by elgatito** [comment]
providers.json

**Comment by Jezze83** [comment]
Why i dont see my custom provider in burst settings? I also added that to burst settings.xml

**Comment by Jezze83** [comment]
I already checked how other providers are made and i think i know how those works. For somehow i dont know why i dont get it working.

**Comment by elgatito** [comment]
@Jezze83  if you enable debug information in Burst Kodi settings - you will see in the log the ehp query and it's result.

**Comment by sapiora** [comment]
Can't show all the private trackers. When I start scroll down the list, I get to TorrentLeech and can't go down the list. When I am at the first tracker (0day) and scroll up, I get to the last one (Кинозал) but can't scroll up; when I hit the up button it goes to right options (Cancel). My device is Sony Android TV XE9005 stock firmware.

**Comment by elgatito** [comment]
@sapiora Kodi was limited number of settings.

**Comment by sapiora** [comment]
@elgatito I don't have this issue with the Public trackers option.

**Comment by elgatito** [comment]
@sapiora because number of options is different in different categories.

**Comment by sapiora** [comment]
@elgatito I am sorry. I was referring to Elementum Burst's Settings. If that matters.

**Comment by sapiora** [comment]
Also, the Elementum crashes when I go to Movies -> My History.
